repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff .
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy rtclient
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: tests
        entry: pytest tests/
        language: system
        always_run: true
        pass_filenames: false
